Tc=121
TcHonor=124
CmaxHonor=20
Cmax=17
ThesisCourseCode=CN4740
LastTermCodes=CN4740;HEL2501;HEL2602
SummerCmax=17
SummerConcNMax=3
SummerConcNMaxHonor=4
Summer12ConcNMax=2
Summer12ConcNMaxHonor=2
SummerCmaxHonor=20
Smax=40
MaxLETerm=12
FreshmanMaxNumCoursesPerTerm=3
MinNumCourses4Sophomore=3
ProgramCodes2Maximize=CN
ProgramCode=CN
AllowEdit=true
#SCIP_path=/Users/itc/apps/SCIPOptSuite800/bin/scip.exe
SCIP_path=./bin/SCIPOptSuite800/bin/scip.exe
CourseCSVFileHeader=#Code;Name;Synonyms;Credits;Pre-requisites;Co-requisites;Terms Offered;Schedule Name;Difficulty Level
